"""Pipeline state vocabulary shared by persistence, application, and GUI."""

from __future__ import annotations

from enum import StrEnum


class PipelineStage(StrEnum):
    CREATED = "CREATED"
    IMPORTING = "IMPORTING"
    ANALYZING = "ANALYZING"
    NORMALIZING = "NORMALIZING"
    DEDUPLICATING = "DEDUPLICATING"
    TAGGING = "TAGGING"
    CAPTIONING = "CAPTIONING"
    DATASET_REVIEW = "DATASET_REVIEW"
    PLANNING = "PLANNING"
    CODEX_PRETRAIN_REVIEW = "CODEX_PRETRAIN_REVIEW"
    PREFLIGHT = "PREFLIGHT"
    TRAINING = "TRAINING"
    SCREENING = "SCREENING"
    WEIGHT_SWEEP = "WEIGHT_SWEEP"
    MULTI_SEED_VALIDATION = "MULTI_SEED_VALIDATION"
    FINAL_EVALUATION = "FINAL_EVALUATION"
    CODEX_FINAL_REVIEW = "CODEX_FINAL_REVIEW"
    SELECTING = "SELECTING"
    PACKAGING = "PACKAGING"
    READY = "READY"


class StageStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class RunStatus(StrEnum):
    ACTIVE = "ACTIVE"
    FAILED_RECOVERABLE = "FAILED_RECOVERABLE"
    FAILED_FATAL = "FAILED_FATAL"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"
